@extends('layouts.admin')
@section('judul','Pelanggan')
@section('breadcrumb')<div class="d-flex align-items-center justify-content-between py-3"><div><h4 class="fs-18 fw-semibold mb-1">Pelanggan</h4><p class="text-muted mb-0">Jenis pelanggan, kontak, kredit, potongan, serta alamat pengiriman/proyek.</p></div>@if(auth()->user()->memilikiHakAkses('MASTER_PELANGGAN_KELOLA',session('id_cabang_aktif')))<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalTambahPelanggan"><i data-lucide="user-plus" class="me-1"></i>Tambah Pelanggan</button>@endif</div>@endsection
@section('content')
@if(session('berhasil'))<div class="alert alert-success">{{ session('berhasil') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card"><div class="card-header"><form class="row g-2"><div class="col-md-5"><input class="form-control" name="pencarian" value="{{ $pencarian }}" placeholder="Kode, nama, kontak, atau WhatsApp"></div><div class="col-auto"><button class="btn btn-primary">Cari</button></div>@if($pencarian)<div class="col-auto"><a href="{{ route('pelanggan.index') }}" class="btn btn-light">Reset</a></div>@endif</form></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Pelanggan</th><th>Jenis</th><th>Kontak</th><th>Piutang</th><th>Alamat</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
@forelse($pelanggan as $item)<tr><td><strong>{{ $item->nama_pelanggan }}</strong><br><small class="text-muted">{{ $item->kode_pelanggan }}</small></td><td>{{ $item->nama_jenis_pelanggan }}</td><td>{{ $item->nomor_whatsapp ?: $item->telepon ?: '-' }}<br><small class="text-muted">{{ $item->nama_kontak ?: '-' }}</small></td><td>Rp{{ number_format($item->batas_piutang,0,',','.') }}<br><small class="text-muted">{{ $item->lama_jatuh_tempo }} hari · diskon {{ number_format($item->potongan_persen,2,',','.') }}%</small></td><td>{{ \Illuminate\Support\Str::limit($item->alamat_utama ?: '-',45) }}<br><small class="text-muted">{{ ($alamat[$item->id_pelanggan] ?? collect())->count() }} alamat tambahan</small></td><td><span class="badge badge-soft-{{ $item->status_aktif?'success':'danger' }}">{{ $item->status_aktif?'Aktif':'Nonaktif' }}</span></td><td class="text-end text-nowrap">@if(auth()->user()->memilikiHakAkses('MASTER_PELANGGAN_KELOLA',session('id_cabang_aktif')))<button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalEditPelanggan{{ $item->id_pelanggan }}">Edit</button>@if($item->kode_pelanggan!=='UMUM')<form class="d-inline" method="POST" action="{{ route('pelanggan.status',$item->id_pelanggan) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-{{ $item->status_aktif?'danger':'success' }}" onclick="return confirm('Ubah status pelanggan?')">{{ $item->status_aktif?'Nonaktifkan':'Aktifkan' }}</button></form>@endif @endif</td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada pelanggan.</td></tr>@endforelse
</tbody></table></div><div class="card-footer">{{ $pelanggan->links() }}</div></div>
@if(auth()->user()->memilikiHakAkses('MASTER_PELANGGAN_KELOLA',session('id_cabang_aktif')))
<div class="modal fade" id="modalTambahPelanggan" tabindex="-1"><div class="modal-dialog modal-xl"><div class="modal-content"><form method="POST" action="{{ route('pelanggan.simpan') }}">@csrf<div class="modal-header"><h5 class="modal-title">Tambah Pelanggan</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('pelanggan.partials.form',['item'=>null,'prefix'=>'tambah'])</div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan</button></div></form></div></div></div>
@foreach($pelanggan as $item)<div class="modal fade" id="modalEditPelanggan{{ $item->id_pelanggan }}" tabindex="-1"><div class="modal-dialog modal-xl"><div class="modal-content"><form method="POST" action="{{ route('pelanggan.ubah',$item->id_pelanggan) }}">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Edit {{ $item->nama_pelanggan }}</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('pelanggan.partials.form',['item'=>$item,'prefix'=>'edit'.$item->id_pelanggan])</div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div></div>@endforeach
@endif
@endsection
@push('scripts')<script>
function aturNamaAlamat(wadah){wadah.querySelectorAll('[data-baris-alamat]').forEach((baris,index)=>baris.querySelectorAll('[data-field]').forEach(field=>field.name=`alamat[${index}][${field.dataset.field}]`));}
document.querySelectorAll('[data-wadah-alamat]').forEach(aturNamaAlamat);
document.addEventListener('click',event=>{const tambah=event.target.closest('[data-tambah-alamat]');if(tambah){const wadah=document.getElementById(tambah.dataset.target);const baris=wadah.querySelector('[data-baris-alamat]').cloneNode(true);baris.querySelectorAll('input,textarea').forEach(field=>{if(field.type==='checkbox')field.checked=false;else field.value='';});wadah.appendChild(baris);aturNamaAlamat(wadah);}const hapus=event.target.closest('[data-hapus-alamat]');if(hapus){const wadah=hapus.closest('[data-wadah-alamat]');if(wadah.querySelectorAll('[data-baris-alamat]').length>1)hapus.closest('[data-baris-alamat]').remove();aturNamaAlamat(wadah);}});
</script>@endpush
