@extends('layouts.admin')
@section('judul','Gudang dan Lokasi')
@section('breadcrumb')
<div class="d-flex align-items-center justify-content-between py-3"><div><h4 class="fs-18 fw-semibold mb-1">Gudang dan Lokasi</h4><p class="text-muted mb-0">Gudang per cabang, lokasi bertingkat, serta area khusus rusak dan retur.</p></div>@if(auth()->user()->memilikiHakAkses('MASTER_GUDANG_KELOLA',session('id_cabang_aktif')))<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalTambahGudang"><i data-lucide="warehouse" class="me-1"></i>Tambah Gudang</button>@endif</div>
@endsection
@section('content')
@if(session('berhasil'))<div class="alert alert-success">{{ session('berhasil') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card mb-3"><div class="card-header"><form class="row g-2"><div class="col-md-5"><input class="form-control" name="pencarian" value="{{ $pencarian }}" placeholder="Kode, nama gudang, atau penanggung jawab"></div><div class="col-auto"><button class="btn btn-primary">Cari</button></div>@if($pencarian)<div class="col-auto"><a class="btn btn-light" href="{{ route('gudang.index') }}">Reset</a></div>@endif</form></div></div>
<div class="row">
@forelse($gudang as $item)
<div class="col-xl-6"><div class="card"><div class="card-header d-flex justify-content-between align-items-start"><div><h5 class="mb-1">{{ $item->nama_gudang }}</h5><span class="badge badge-soft-primary">{{ $item->kode_gudang }}</span> <span class="badge badge-soft-info">{{ $item->jenis_gudang }}</span> <span class="badge badge-soft-{{ $item->status_aktif?'success':'danger' }}">{{ $item->status_aktif?'Aktif':'Nonaktif' }}</span></div>@if(auth()->user()->memilikiHakAkses('MASTER_GUDANG_KELOLA',session('id_cabang_aktif')))<div class="text-nowrap"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalEditGudang{{ $item->id_gudang }}">Edit</button><button class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target="#modalTambahLokasi{{ $item->id_gudang }}">Lokasi +</button>@if(!in_array($item->jenis_gudang,['RUSAK','RETUR']))<form class="d-inline" method="POST" action="{{ route('gudang.status',$item->id_gudang) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-danger" onclick="return confirm('Ubah status gudang?')">Status</button></form>@endif</div>@endif</div>
<div class="card-body"><p class="text-muted">{{ $item->alamat ?: 'Alamat belum diisi.' }}<br>{{ $item->nama_penanggung_jawab ?: 'Belum ada penanggung jawab' }} {{ $item->telepon ? '· '.$item->telepon : '' }}</p><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Kode</th><th>Lokasi</th><th>Jenis</th><th>Induk</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($lokasi[$item->id_gudang] ?? collect() as $baris)<tr><td>{{ $baris->kode_lokasi }}</td><td>{{ $baris->nama_lokasi }}</td><td>{{ $baris->jenis_lokasi }}</td><td>{{ $baris->nama_lokasi_induk ?: '-' }}</td><td>{{ $baris->status_aktif?'Aktif':'Nonaktif' }}</td><td class="text-end text-nowrap">@if(auth()->user()->memilikiHakAkses('MASTER_GUDANG_KELOLA',session('id_cabang_aktif')))<button class="btn btn-xs btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalEditLokasi{{ $baris->id_lokasi_gudang }}">Edit</button>@if(!(in_array($item->jenis_gudang,['RUSAK','RETUR']) && $baris->jenis_lokasi==='AREA_UMUM'))<form class="d-inline" method="POST" action="{{ route('gudang.lokasi.status',[$item->id_gudang,$baris->id_lokasi_gudang]) }}">@csrf @method('PATCH')<button class="btn btn-xs btn-outline-warning">Status</button></form>@endif @endif</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">Belum ada lokasi.</td></tr>@endforelse
</tbody></table></div></div></div></div>
@empty<div class="col-12"><div class="alert alert-info">Belum ada gudang pada cabang aktif.</div></div>@endforelse
</div>
<div>{{ $gudang->links() }}</div>
@if(auth()->user()->memilikiHakAkses('MASTER_GUDANG_KELOLA',session('id_cabang_aktif')))
<div class="modal fade" id="modalTambahGudang" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST" action="{{ route('gudang.simpan') }}">@csrf<div class="modal-header"><h5 class="modal-title">Tambah Gudang</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Kode</label><input class="form-control" name="kode_gudang" required></div><div class="col-md-8"><label class="form-label">Nama Gudang</label><input class="form-control" name="nama_gudang" required></div><div class="col-md-4"><label class="form-label">Jenis</label><select class="form-select" name="jenis_gudang">@foreach(['UTAMA','TOKO','TRANSIT','RUSAK','RETUR'] as $jenis)<option>{{ $jenis }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Penanggung Jawab</label><input class="form-control" name="nama_penanggung_jawab"></div><div class="col-md-4"><label class="form-label">Telepon</label><input class="form-control" name="telepon"></div><div class="col-12"><label class="form-label">Alamat</label><textarea class="form-control" name="alamat"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan</button></div></form></div></div></div>
@foreach($gudang as $item)
<div class="modal fade" id="modalEditGudang{{ $item->id_gudang }}" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST" action="{{ route('gudang.ubah',$item->id_gudang) }}">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Edit Gudang</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Kode</label><input class="form-control" name="kode_gudang" value="{{ $item->kode_gudang }}" required></div><div class="col-md-8"><label class="form-label">Nama Gudang</label><input class="form-control" name="nama_gudang" value="{{ $item->nama_gudang }}" required></div><div class="col-md-4"><label class="form-label">Jenis</label><select class="form-select" name="jenis_gudang">@foreach(['UTAMA','TOKO','TRANSIT','RUSAK','RETUR'] as $jenis)<option @selected($item->jenis_gudang===$jenis)>{{ $jenis }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Penanggung Jawab</label><input class="form-control" name="nama_penanggung_jawab" value="{{ $item->nama_penanggung_jawab }}"></div><div class="col-md-4"><label class="form-label">Telepon</label><input class="form-control" name="telepon" value="{{ $item->telepon }}"></div><div class="col-12"><label class="form-label">Alamat</label><textarea class="form-control" name="alamat">{{ $item->alamat }}</textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan</button></div></form></div></div></div>
<div class="modal fade" id="modalTambahLokasi{{ $item->id_gudang }}" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('gudang.lokasi.simpan',$item->id_gudang) }}">@csrf<div class="modal-header"><h5 class="modal-title">Tambah Lokasi · {{ $item->nama_gudang }}</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Kode</label><input class="form-control" name="kode_lokasi" required></div><div class="mb-3"><label class="form-label">Nama Lokasi</label><input class="form-control" name="nama_lokasi" required></div><div class="mb-3"><label class="form-label">Jenis</label><select class="form-select" name="jenis_lokasi">@foreach(['AREA_UMUM','ZONA','RAK','BARIS','TINGKAT'] as $jenis)<option>{{ $jenis }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Induk</label><select class="form-select" name="id_lokasi_induk"><option value="">Tanpa induk</option>@foreach($lokasi[$item->id_gudang] ?? collect() as $opsi)<option value="{{ $opsi->id_lokasi_gudang }}">{{ $opsi->nama_lokasi }}</option>@endforeach</select></div><div><label class="form-label">Keterangan</label><textarea class="form-control" name="keterangan"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan</button></div></form></div></div></div>
@foreach($lokasi[$item->id_gudang] ?? collect() as $baris)<div class="modal fade" id="modalEditLokasi{{ $baris->id_lokasi_gudang }}" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('gudang.lokasi.ubah',[$item->id_gudang,$baris->id_lokasi_gudang]) }}">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Edit Lokasi</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Kode</label><input class="form-control" name="kode_lokasi" value="{{ $baris->kode_lokasi }}" required></div><div class="mb-3"><label class="form-label">Nama Lokasi</label><input class="form-control" name="nama_lokasi" value="{{ $baris->nama_lokasi }}" required></div><div class="mb-3"><label class="form-label">Jenis</label><select class="form-select" name="jenis_lokasi">@foreach(['AREA_UMUM','ZONA','RAK','BARIS','TINGKAT'] as $jenis)<option @selected($baris->jenis_lokasi===$jenis)>{{ $jenis }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Induk</label><select class="form-select" name="id_lokasi_induk"><option value="">Tanpa induk</option>@foreach($lokasi[$item->id_gudang] ?? collect() as $opsi)@continue($opsi->id_lokasi_gudang===$baris->id_lokasi_gudang)<option value="{{ $opsi->id_lokasi_gudang }}" @selected($baris->id_lokasi_induk===$opsi->id_lokasi_gudang)>{{ $opsi->nama_lokasi }}</option>@endforeach</select></div><div><label class="form-label">Keterangan</label><textarea class="form-control" name="keterangan">{{ $baris->keterangan }}</textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan</button></div></form></div></div></div>@endforeach
@endforeach
@endif
@endsection
