<div class="modal fade" id="modalRetur" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-scrollable">
        <form class="modal-content" method="POST" action="{{ route('penjualan.retur.simpan') }}">
            @csrf
            <div class="modal-header"><h5 class="modal-title">Retur Penjualan</h5><button class="btn-close" data-bs-dismiss="modal" type="button"></button></div>
            <div class="modal-body">
                <div class="row g-3 mb-3"><div class="col-md-3"><label class="form-label">Penjualan</label><select class="form-select" name="id_penjualan" required><option value="">Pilih</option>@foreach($penjualanPilihan as $p)<option value="{{ $p->id_penjualan }}">{{ $p->nomor_penjualan }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Gudang Retur</label><select class="form-select" name="id_gudang" required><option value="">Pilih</option>@foreach($gudangPilihan as $g)<option value="{{ $g->id_gudang }}">{{ $g->nama_gudang }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Tanggal</label><input class="form-control" type="date" name="tanggal_retur" value="{{ now()->toDateString() }}" required></div><div class="col-md-4"><label class="form-label">Pengembalian Dana</label><select class="form-select" name="cara_pengembalian_dana"><option>POTONG_PIUTANG</option><option>TUNAI</option><option>TRANSFER</option><option>PENGGANTI_BARANG</option></select></div><div class="col-12"><label class="form-label">Alasan</label><textarea class="form-control" name="alasan_retur" rows="2" required></textarea></div></div>
                <div class="table-responsive"><table class="table table-bordered align-middle"><thead><tr><th>Detail Penjualan</th><th>Barang</th><th>Lokasi</th><th>Jumlah</th><th>Harga</th><th>Kondisi</th><th>Dijual Kembali</th></tr></thead><tbody><tr><td><select class="form-select" name="detail[0][id_penjualan_detail]" required><option value="">Pilih</option>@foreach($penjualanDetailPilihan as $d)<option value="{{ $d->id_penjualan_detail }}">{{ $d->nomor_penjualan }} — {{ $d->nama_barang }}</option>@endforeach</select></td><td><select class="form-select" name="detail[0][id_barang_satuan]" required><option value="">Pilih</option>@foreach($barangSatuanPilihan as $b)<option value="{{ $b->id_barang_satuan }}">{{ $b->nama_barang }} ({{ $b->nama_satuan }})</option>@endforeach</select></td><td><select class="form-select" name="detail[0][id_lokasi_gudang]" required><option value="">Pilih</option>@foreach($lokasiPilihan as $l)<option value="{{ $l->id_lokasi_gudang }}">{{ $l->nama_gudang }} — {{ $l->nama_lokasi }}</option>@endforeach</select></td><td><input class="form-control" name="detail[0][jumlah]" type="number" min="0.001" step="0.001" required></td><td><input class="form-control" name="detail[0][harga_satuan]" type="number" min="0" step="0.01" required></td><td><select class="form-select" name="detail[0][kondisi_barang]"><option>BAIK</option><option>RUSAK</option><option>CACAT</option><option>SALAH_KIRIM</option><option>LAINNYA</option></select></td><td><select class="form-select" name="detail[0][bisa_dijual_kembali]"><option value="1">Ya</option><option value="0">Tidak</option></select></td></tr></tbody></table></div>
            </div>
            <div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Tutup</button><button class="btn btn-danger">Simpan Draf</button></div>
        </form>
    </div>
</div>
