<?php

return [
    'maksimum_kilobita' => 10240,
    'ekstensi_diizinkan' => ['pdf', 'jpg', 'jpeg', 'png', 'webp', 'csv', 'xls', 'xlsx', 'doc', 'docx'],

    'dokumen' => [
        'STOK_AWAL' => [
            'label' => 'Stok Awal',
            'tabel' => 'stok_awal',
            'kunci' => 'id_stok_awal',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'STOK_AWAL_KELOLA',
        ],
        'TRANSFER_STOK' => [
            'label' => 'Transfer Stok',
            'tabel' => 'transfer_stok',
            'kunci' => 'id_transfer_stok',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'TRANSFER_STOK_KELOLA',
        ],
        'STOK_OPNAME' => [
            'label' => 'Stok Opname',
            'tabel' => 'stok_opname',
            'kunci' => 'id_stok_opname',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'STOK_OPNAME_KELOLA',
        ],
        'PENYESUAIAN_STOK' => [
            'label' => 'Penyesuaian Stok',
            'tabel' => 'penyesuaian_stok',
            'kunci' => 'id_penyesuaian_stok',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PENYESUAIAN_STOK_KELOLA',
        ],
        'PERMINTAAN_PEMBELIAN' => [
            'label' => 'Permintaan Pembelian',
            'tabel' => 'permintaan_pembelian',
            'kunci' => 'id_permintaan_pembelian',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PEMBELIAN_LIHAT',
        ],
        'PESANAN_PEMBELIAN' => [
            'label' => 'Pesanan Pembelian',
            'tabel' => 'pesanan_pembelian',
            'kunci' => 'id_pesanan_pembelian',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PEMBELIAN_LIHAT',
        ],
        'PENERIMAAN_BARANG' => [
            'label' => 'Penerimaan Barang',
            'tabel' => 'penerimaan_barang',
            'kunci' => 'id_penerimaan_barang',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PEMBELIAN_LIHAT',
        ],
        'FAKTUR_PEMBELIAN' => [
            'label' => 'Faktur Pembelian',
            'tabel' => 'faktur_pembelian',
            'kunci' => 'id_faktur_pembelian',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PEMBELIAN_LIHAT',
        ],
        'RETUR_PEMBELIAN' => [
            'label' => 'Retur Pembelian',
            'tabel' => 'retur_pembelian',
            'kunci' => 'id_retur_pembelian',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PEMBELIAN_LIHAT',
        ],
        'PEMBAYARAN_HUTANG' => [
            'label' => 'Pembayaran Hutang',
            'tabel' => 'pembayaran_hutang',
            'kunci' => 'id_pembayaran_hutang',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'HUTANG_PEMASOK_LIHAT',
        ],
        'PENAWARAN_PENJUALAN' => [
            'label' => 'Penawaran Penjualan',
            'tabel' => 'penawaran_penjualan',
            'kunci' => 'id_penawaran_penjualan',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PENJUALAN_LIHAT',
        ],
        'PESANAN_PENJUALAN' => [
            'label' => 'Pesanan Penjualan',
            'tabel' => 'pesanan_penjualan',
            'kunci' => 'id_pesanan_penjualan',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PENJUALAN_LIHAT',
        ],
        'PENJUALAN' => [
            'label' => 'Penjualan',
            'tabel' => 'penjualan',
            'kunci' => 'id_penjualan',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PENJUALAN_LIHAT',
        ],
        'PENGIRIMAN' => [
            'label' => 'Pengiriman',
            'tabel' => 'pengiriman',
            'kunci' => 'id_pengiriman',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PENJUALAN_LIHAT',
        ],
        'RETUR_PENJUALAN' => [
            'label' => 'Retur Penjualan',
            'tabel' => 'retur_penjualan',
            'kunci' => 'id_retur_penjualan',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PENJUALAN_LIHAT',
        ],
        'PEMBAYARAN_PIUTANG' => [
            'label' => 'Pembayaran Piutang',
            'tabel' => 'pembayaran_piutang',
            'kunci' => 'id_pembayaran_piutang',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'PIUTANG_PELANGGAN_LIHAT',
        ],
        'TRANSAKSI_KAS' => [
            'label' => 'Transaksi Kas/Bank',
            'tabel' => 'transaksi_kas',
            'kunci' => 'id_transaksi_kas',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'KEUANGAN_LIHAT',
        ],
        'JURNAL_UMUM' => [
            'label' => 'Jurnal Umum',
            'tabel' => 'jurnal_umum',
            'kunci' => 'id_jurnal_umum',
            'kolom_cabang' => 'id_cabang',
            'izin_modul' => 'KEUANGAN_LIHAT',
        ],
    ],
];
