<?php

return [
    'kategori-barang' => [
        'judul' => 'Kategori Barang',
        'deskripsi' => 'Kelola kategori bertingkat untuk pengelompokan barang.',
        'tabel' => 'kategori_barang',
        'kunci' => 'id_kategori_barang',
        'kode' => 'kode_kategori',
        'pencarian' => ['kode_kategori', 'nama_kategori'],
        'urutan' => ['urutan_tampil', 'nama_kategori'],
        'izin_lihat' => 'MASTER_BARANG_LIHAT',
        'izin_kelola' => 'MASTER_BARANG_KELOLA',
        'kolom' => [
            'kode_kategori' => ['label' => 'Kode', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:30'], 'unik' => true],
            'nama_kategori' => ['label' => 'Nama Kategori', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:150']],
            'id_kategori_induk' => ['label' => 'Kategori Induk', 'tipe' => 'relation', 'nullable' => true, 'relasi' => ['tabel' => 'kategori_barang', 'kunci' => 'id_kategori_barang', 'label' => 'nama_kategori']],
            'urutan_tampil' => ['label' => 'Urutan Tampil', 'tipe' => 'number', 'aturan' => ['required', 'integer', 'min:0', 'max:4294967295'], 'default' => 0],
            'keterangan' => ['label' => 'Keterangan', 'tipe' => 'textarea', 'aturan' => ['nullable', 'string']],
        ],
    ],
    'merek-barang' => [
        'judul' => 'Merek Barang',
        'deskripsi' => 'Kelola merek atau produsen barang.',
        'tabel' => 'merek_barang',
        'kunci' => 'id_merek_barang',
        'kode' => 'kode_merek',
        'pencarian' => ['kode_merek', 'nama_merek'],
        'urutan' => ['nama_merek'],
        'izin_lihat' => 'MASTER_BARANG_LIHAT',
        'izin_kelola' => 'MASTER_BARANG_KELOLA',
        'kolom' => [
            'kode_merek' => ['label' => 'Kode', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:30'], 'unik' => true],
            'nama_merek' => ['label' => 'Nama Merek', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:150']],
            'keterangan' => ['label' => 'Keterangan', 'tipe' => 'textarea', 'aturan' => ['nullable', 'string']],
        ],
    ],
    'satuan' => [
        'judul' => 'Satuan',
        'deskripsi' => 'Jumlah desimal menjadi sumber aturan validasi kuantitas seluruh sistem.',
        'tabel' => 'satuan',
        'kunci' => 'id_satuan',
        'kode' => 'kode_satuan',
        'pencarian' => ['kode_satuan', 'nama_satuan'],
        'urutan' => ['nama_satuan'],
        'izin_lihat' => 'MASTER_BARANG_LIHAT',
        'izin_kelola' => 'MASTER_BARANG_KELOLA',
        'kolom' => [
            'kode_satuan' => ['label' => 'Kode', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:20'], 'unik' => true],
            'nama_satuan' => ['label' => 'Nama Satuan', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:100'], 'unik' => true],
            'jumlah_desimal' => ['label' => 'Jumlah Desimal', 'tipe' => 'number', 'aturan' => ['required', 'integer', 'min:0', 'max:3'], 'default' => 0],
        ],
    ],
    'jenis-pelanggan' => [
        'judul' => 'Jenis Pelanggan',
        'deskripsi' => 'Kelola segmentasi pelanggan dan nilai bawaan kredit.',
        'tabel' => 'jenis_pelanggan',
        'kunci' => 'id_jenis_pelanggan',
        'kode' => 'kode_jenis_pelanggan',
        'pencarian' => ['kode_jenis_pelanggan', 'nama_jenis_pelanggan'],
        'urutan' => ['nama_jenis_pelanggan'],
        'izin_lihat' => 'MASTER_PELANGGAN_LIHAT',
        'izin_kelola' => 'MASTER_PELANGGAN_KELOLA',
        'kolom' => [
            'kode_jenis_pelanggan' => ['label' => 'Kode', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:30'], 'unik' => true],
            'nama_jenis_pelanggan' => ['label' => 'Nama Jenis', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:100']],
            'potongan_persen_bawaan' => ['label' => 'Potongan Bawaan (%)', 'tipe' => 'decimal', 'aturan' => ['required', 'numeric', 'min:0', 'max:100'], 'default' => 0],
            'batas_piutang_bawaan' => ['label' => 'Batas Piutang Bawaan', 'tipe' => 'decimal', 'aturan' => ['required', 'numeric', 'min:0'], 'default' => 0],
            'lama_jatuh_tempo_bawaan' => ['label' => 'Jatuh Tempo Bawaan (hari)', 'tipe' => 'number', 'aturan' => ['required', 'integer', 'min:0', 'max:65535'], 'default' => 0],
        ],
    ],
    'pemasok' => [
        'judul' => 'Pemasok',
        'deskripsi' => 'Kelola identitas, kontak, rekening, dan kebijakan hutang pemasok.',
        'tabel' => 'pemasok',
        'kunci' => 'id_pemasok',
        'kode' => 'kode_pemasok',
        'pencarian' => ['kode_pemasok', 'nama_pemasok', 'nama_kontak', 'nomor_whatsapp'],
        'urutan' => ['nama_pemasok'],
        'izin_lihat' => 'MASTER_PEMASOK_LIHAT',
        'izin_kelola' => 'MASTER_PEMASOK_KELOLA',
        'kolom' => [
            'kode_pemasok' => ['label' => 'Kode', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:40'], 'unik' => true],
            'nama_pemasok' => ['label' => 'Nama Pemasok', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:200']],
            'nomor_pokok_wajib_pajak' => ['label' => 'NPWP', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:40']],
            'nama_kontak' => ['label' => 'Nama Kontak', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:150']],
            'telepon' => ['label' => 'Telepon', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:30']],
            'nomor_whatsapp' => ['label' => 'WhatsApp', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:30']],
            'surel' => ['label' => 'Surel', 'tipe' => 'email', 'aturan' => ['nullable', 'email', 'max:150']],
            'alamat' => ['label' => 'Alamat', 'tipe' => 'textarea', 'aturan' => ['nullable', 'string']],
            'provinsi' => ['label' => 'Provinsi', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:100']],
            'kabupaten_kota' => ['label' => 'Kabupaten/Kota', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:100']],
            'kecamatan' => ['label' => 'Kecamatan', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:100']],
            'kelurahan' => ['label' => 'Kelurahan', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:100']],
            'kode_pos' => ['label' => 'Kode Pos', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:10']],
            'nama_bank' => ['label' => 'Nama Bank', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:100']],
            'nomor_rekening' => ['label' => 'Nomor Rekening', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:100']],
            'nama_pemilik_rekening' => ['label' => 'Pemilik Rekening', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:150']],
            'batas_hutang' => ['label' => 'Batas Hutang', 'tipe' => 'decimal', 'aturan' => ['required', 'numeric', 'min:0'], 'default' => 0],
            'lama_jatuh_tempo' => ['label' => 'Jatuh Tempo (hari)', 'tipe' => 'number', 'aturan' => ['required', 'integer', 'min:0', 'max:65535'], 'default' => 0],
        ],
    ],
    'kas-bank' => [
        'judul' => 'Kas dan Bank',
        'deskripsi' => 'Kelola kas dan rekening bank per cabang aktif.',
        'tabel' => 'kas_bank',
        'kunci' => 'id_kas_bank',
        'kode' => 'kode_kas_bank',
        'cabang' => true,
        'pencarian' => ['kode_kas_bank', 'nama_kas_bank', 'nomor_rekening'],
        'urutan' => ['nama_kas_bank'],
        'izin_lihat' => 'MASTER_KEUANGAN_LIHAT',
        'izin_kelola' => 'MASTER_KEUANGAN_KELOLA',
        'kolom' => [
            'kode_kas_bank' => ['label' => 'Kode', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:30'], 'unik' => true, 'unik_cabang' => true],
            'nama_kas_bank' => ['label' => 'Nama Kas/Bank', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:150']],
            'jenis_kas_bank' => ['label' => 'Jenis', 'tipe' => 'select', 'aturan' => ['required', 'in:KAS,BANK'], 'opsi' => ['KAS' => 'Kas', 'BANK' => 'Bank']],
            'nama_bank' => ['label' => 'Nama Bank', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:100']],
            'nomor_rekening' => ['label' => 'Nomor Rekening', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:100']],
            'nama_pemilik_rekening' => ['label' => 'Pemilik Rekening', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:150']],
            'saldo_awal' => ['label' => 'Saldo Awal', 'tipe' => 'decimal', 'aturan' => ['required', 'numeric'], 'default' => 0],
            'tanggal_saldo_awal' => ['label' => 'Tanggal Saldo Awal', 'tipe' => 'date', 'aturan' => ['nullable', 'date']],
        ],
    ],
    'metode-pembayaran' => [
        'judul' => 'Metode Pembayaran',
        'deskripsi' => 'Kelola metode dan biaya pembayaran.',
        'tabel' => 'metode_pembayaran',
        'kunci' => 'id_metode_pembayaran',
        'kode' => 'kode_metode_pembayaran',
        'pencarian' => ['kode_metode_pembayaran', 'nama_metode_pembayaran'],
        'urutan' => ['nama_metode_pembayaran'],
        'izin_lihat' => 'MASTER_KEUANGAN_LIHAT',
        'izin_kelola' => 'MASTER_KEUANGAN_KELOLA',
        'kolom' => [
            'kode_metode_pembayaran' => ['label' => 'Kode', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:30'], 'unik' => true],
            'nama_metode_pembayaran' => ['label' => 'Nama Metode', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:100']],
            'kelompok_pembayaran' => ['label' => 'Kelompok', 'tipe' => 'select', 'aturan' => ['required', 'in:TUNAI,TRANSFER,KARTU,DOMPET_DIGITAL,TEMPO,LAINNYA'], 'opsi' => ['TUNAI' => 'Tunai', 'TRANSFER' => 'Transfer', 'KARTU' => 'Kartu', 'DOMPET_DIGITAL' => 'Dompet Digital', 'TEMPO' => 'Tempo', 'LAINNYA' => 'Lainnya']],
            'biaya_persen' => ['label' => 'Biaya (%)', 'tipe' => 'decimal', 'aturan' => ['required', 'numeric', 'min:0', 'max:100'], 'default' => 0],
            'biaya_tetap' => ['label' => 'Biaya Tetap', 'tipe' => 'decimal', 'aturan' => ['required', 'numeric', 'min:0'], 'default' => 0],
        ],
    ],
    'kategori-biaya' => [
        'judul' => 'Kategori Biaya',
        'deskripsi' => 'Kelola kategori biaya bertingkat.',
        'tabel' => 'kategori_biaya',
        'kunci' => 'id_kategori_biaya',
        'kode' => 'kode_kategori_biaya',
        'pencarian' => ['kode_kategori_biaya', 'nama_kategori_biaya'],
        'urutan' => ['nama_kategori_biaya'],
        'izin_lihat' => 'MASTER_KEUANGAN_LIHAT',
        'izin_kelola' => 'MASTER_KEUANGAN_KELOLA',
        'kolom' => [
            'kode_kategori_biaya' => ['label' => 'Kode', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:30'], 'unik' => true],
            'nama_kategori_biaya' => ['label' => 'Nama Kategori', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:150']],
            'id_kategori_induk' => ['label' => 'Kategori Induk', 'tipe' => 'relation', 'nullable' => true, 'relasi' => ['tabel' => 'kategori_biaya', 'kunci' => 'id_kategori_biaya', 'label' => 'nama_kategori_biaya']],
            'keterangan' => ['label' => 'Keterangan', 'tipe' => 'textarea', 'aturan' => ['nullable', 'string']],
        ],
    ],
    'armada' => [
        'judul' => 'Armada',
        'deskripsi' => 'Kelola kendaraan pengiriman per cabang.',
        'tabel' => 'armada',
        'kunci' => 'id_armada',
        'kode' => 'nomor_polisi',
        'cabang' => true,
        'pencarian' => ['nomor_polisi', 'jenis_kendaraan', 'merek_kendaraan'],
        'urutan' => ['nomor_polisi'],
        'izin_lihat' => 'MASTER_ARMADA_LIHAT',
        'izin_kelola' => 'MASTER_ARMADA_KELOLA',
        'kolom' => [
            'nomor_polisi' => ['label' => 'Nomor Polisi', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:30'], 'unik' => true],
            'jenis_kendaraan' => ['label' => 'Jenis Kendaraan', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:100']],
            'merek_kendaraan' => ['label' => 'Merek', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:100']],
            'tipe_kendaraan' => ['label' => 'Tipe', 'tipe' => 'text', 'aturan' => ['nullable', 'string', 'max:100']],
            'tahun_kendaraan' => ['label' => 'Tahun', 'tipe' => 'number', 'aturan' => ['nullable', 'integer', 'min:1900', 'max:2200']],
            'kapasitas_kilogram' => ['label' => 'Kapasitas (kg)', 'tipe' => 'decimal', 'aturan' => ['required', 'numeric', 'min:0'], 'default' => 0],
            'kapasitas_meter_kubik' => ['label' => 'Kapasitas (m³)', 'tipe' => 'decimal', 'aturan' => ['required', 'numeric', 'min:0'], 'default' => 0],
            'status_kendaraan' => ['label' => 'Status Kendaraan', 'tipe' => 'select', 'aturan' => ['required', 'in:TERSEDIA,DIGUNAKAN,PERAWATAN,NONAKTIF'], 'opsi' => ['TERSEDIA' => 'Tersedia', 'DIGUNAKAN' => 'Digunakan', 'PERAWATAN' => 'Perawatan', 'NONAKTIF' => 'Nonaktif']],
        ],
    ],
    'tarif-pajak' => [
        'judul' => 'Tarif Pajak',
        'deskripsi' => 'Kelola tarif pajak. Data awal non-pajak tetap 0%.',
        'tabel' => 'tarif_pajak',
        'kunci' => 'id_tarif_pajak',
        'kode' => 'kode_tarif_pajak',
        'pencarian' => ['kode_tarif_pajak', 'nama_tarif_pajak'],
        'urutan' => ['nama_tarif_pajak'],
        'izin_lihat' => 'MASTER_PAJAK_LIHAT',
        'izin_kelola' => 'MASTER_PAJAK_KELOLA',
        'kolom' => [
            'kode_tarif_pajak' => ['label' => 'Kode', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:30'], 'unik' => true],
            'nama_tarif_pajak' => ['label' => 'Nama Tarif', 'tipe' => 'text', 'aturan' => ['required', 'string', 'max:100']],
            'persen_pajak' => ['label' => 'Persen Pajak', 'tipe' => 'decimal', 'aturan' => ['required', 'numeric', 'min:0', 'max:100'], 'default' => 0],
            'jenis_pajak' => ['label' => 'Jenis Pajak', 'tipe' => 'select', 'aturan' => ['required', 'in:MASUKAN,KELUARAN,KEDUANYA'], 'opsi' => ['MASUKAN' => 'Masukan', 'KELUARAN' => 'Keluaran', 'KEDUANYA' => 'Keduanya']],
        ],
    ],
];
