@extends('layouts.admin')
@section('judul', 'Master Barang')
@section('breadcrumb')
<div class="d-flex align-items-center justify-content-between py-3"><div><h4 class="fs-18 fw-semibold mb-1">Master Barang</h4><p class="text-muted mb-0">Kategori, merek, satuan alternatif, konversi, barcode, harga acuan, stok minimum/maksimum, barang dan jasa.</p></div>@if(auth()->user()->memilikiHakAkses('MASTER_BARANG_KELOLA', session('id_cabang_aktif')))<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalTambahBarang"><i data-lucide="package-plus" class="me-1"></i>Tambah Barang</button>@endif</div>
@endsection
@section('content')
@if(session('berhasil'))<div class="alert alert-success">{{ session('berhasil') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card"><div class="card-header"><form class="row g-2"><div class="col-md-5"><input class="form-control" name="pencarian" value="{{ $pencarian }}" placeholder="Kode, nama, merek, atau barcode"></div><div class="col-auto"><button class="btn btn-primary">Cari</button></div>@if($pencarian)<div class="col-auto"><a class="btn btn-light" href="{{ route('barang.index') }}">Reset</a></div>@endif</form></div>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Barang/Jasa</th><th>Kategori & Merek</th><th>Satuan Dasar</th><th>Stok Min/Maks</th><th>Satuan & Barcode</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
@forelse($barang as $item)<tr><td><strong>{{ $item->nama_barang }}</strong><br><small class="text-muted">{{ $item->kode_barang }} · {{ $item->jenis_barang }}</small></td><td>{{ $item->nama_kategori }}<br><small class="text-muted">{{ $item->nama_merek ?: 'Tanpa merek' }}</small></td><td>{{ $item->nama_satuan_dasar }}<br><small class="text-muted">{{ $item->jumlah_desimal }} desimal</small></td><td>{{ number_format($item->stok_minimum, $item->jumlah_desimal, ',', '.') }} / {{ number_format($item->stok_maksimum, $item->jumlah_desimal, ',', '.') }}</td><td>@foreach(($satuanBarang[$item->id_barang] ?? collect())->take(3) as $baris)<span class="badge badge-soft-primary me-1">{{ $baris->kode_satuan }}{{ $baris->kode_batang ? ' · '.$baris->kode_batang : '' }}</span>@endforeach</td><td><span class="badge badge-soft-{{ $item->status_aktif ? 'success':'danger' }}">{{ $item->status_aktif ? 'Aktif':'Nonaktif' }}</span></td><td class="text-end text-nowrap">@if(auth()->user()->memilikiHakAkses('MASTER_BARANG_KELOLA', session('id_cabang_aktif')))<button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalEditBarang{{ $item->id_barang }}">Edit</button><form class="d-inline" method="POST" action="{{ route('barang.status',$item->id_barang) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-{{ $item->status_aktif ? 'danger':'success' }}" onclick="return confirm('Ubah status barang ini?')">{{ $item->status_aktif ? 'Nonaktifkan':'Aktifkan' }}</button></form>@endif</td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada barang.</td></tr>@endforelse
</tbody></table></div><div class="card-footer">{{ $barang->links() }}</div></div>
@if(auth()->user()->memilikiHakAkses('MASTER_BARANG_KELOLA', session('id_cabang_aktif')))
<div class="modal fade" id="modalTambahBarang" tabindex="-1"><div class="modal-dialog modal-xl"><div class="modal-content"><form method="POST" action="{{ route('barang.simpan') }}">@csrf<div class="modal-header"><h5 class="modal-title">Tambah Barang/Jasa</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('barang.partials.form',['item'=>null,'prefix'=>'tambah'])</div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan</button></div></form></div></div></div>
@foreach($barang as $item)<div class="modal fade" id="modalEditBarang{{ $item->id_barang }}" tabindex="-1"><div class="modal-dialog modal-xl"><div class="modal-content"><form method="POST" action="{{ route('barang.ubah',$item->id_barang) }}">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Edit {{ $item->nama_barang }}</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('barang.partials.form',['item'=>$item,'prefix'=>'edit'.$item->id_barang])</div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div></div>@endforeach
@endif
@endsection
@push('scripts')
<script>
function aturNamaSatuan(wadah){wadah.querySelectorAll('[data-baris-satuan]').forEach((baris,index)=>{baris.querySelectorAll('[data-field]').forEach(field=>field.name=`satuan_barang[${index}][${field.dataset.field}]`);});}
document.querySelectorAll('[data-wadah-satuan]').forEach(aturNamaSatuan);
document.addEventListener('click',event=>{const tambah=event.target.closest('[data-tambah-satuan]');if(tambah){const wadah=document.getElementById(tambah.dataset.target);const baris=wadah.querySelector('[data-baris-satuan]').cloneNode(true);baris.querySelectorAll('input').forEach(input=>{if(input.type==='checkbox')input.checked=false;else input.value=input.dataset.field==='nilai_konversi'?1:0;});wadah.appendChild(baris);aturNamaSatuan(wadah);}const hapus=event.target.closest('[data-hapus-satuan]');if(hapus){const wadah=hapus.closest('[data-wadah-satuan]');if(wadah.querySelectorAll('[data-baris-satuan]').length>1)hapus.closest('[data-baris-satuan]').remove();aturNamaSatuan(wadah);}});
</script>
@endpush
