@extends('layouts.admin')
@section('judul','Daftar Harga')
@section('breadcrumb')<div class="d-flex align-items-center justify-content-between py-3"><div><h4 class="fs-18 fw-semibold mb-1">Daftar Harga</h4><p class="text-muted mb-0">Harga per cabang, jenis pelanggan, periode aktif, prioritas, minimum kuantitas, dan potongan.</p></div>@if(auth()->user()->memilikiHakAkses('DAFTAR_HARGA_KELOLA',session('id_cabang_aktif')))<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalTambahHarga"><i data-lucide="badge-plus" class="me-1"></i>Tambah Daftar Harga</button>@endif</div>@endsection
@section('content')
@if(session('berhasil'))<div class="alert alert-success">{{ session('berhasil') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="alert alert-info">Periode aktif pada cabang dan jenis pelanggan yang sama tidak boleh bertabrakan. Daftar tanpa jenis pelanggan berlaku untuk semua jenis pelanggan.</div>
<div class="card"><div class="card-header"><form class="row g-2"><div class="col-md-5"><input class="form-control" name="pencarian" value="{{ $pencarian }}" placeholder="Kode, nama daftar, atau jenis pelanggan"></div><div class="col-auto"><button class="btn btn-primary">Cari</button></div>@if($pencarian)<div class="col-auto"><a href="{{ route('daftar-harga.index') }}" class="btn btn-light">Reset</a></div>@endif</form></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Daftar Harga</th><th>Jenis Pelanggan</th><th>Periode</th><th>Prioritas</th><th>Detail</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
@forelse($daftarHarga as $item)<tr><td><strong>{{ $item->nama_daftar_harga }}</strong><br><small class="text-muted">{{ $item->kode_daftar_harga }}</small></td><td>{{ $item->nama_jenis_pelanggan ?: 'Semua jenis' }}</td><td>{{ \Carbon\Carbon::parse($item->tanggal_mulai)->format('d-m-Y') }} s/d {{ $item->tanggal_selesai ? \Carbon\Carbon::parse($item->tanggal_selesai)->format('d-m-Y') : 'Tanpa batas' }}</td><td>{{ $item->prioritas }}</td><td>{{ ($detail[$item->id_daftar_harga] ?? collect())->count() }} baris<br>@foreach(($detail[$item->id_daftar_harga] ?? collect())->take(2) as $baris)<small class="text-muted d-block">{{ $baris->kode_barang }} / {{ $baris->kode_satuan }} · Rp{{ number_format($baris->harga_jual,0,',','.') }}</small>@endforeach</td><td><span class="badge badge-soft-{{ $item->status_aktif?'success':'danger' }}">{{ $item->status_aktif?'Aktif':'Nonaktif' }}</span></td><td class="text-end text-nowrap">@if(auth()->user()->memilikiHakAkses('DAFTAR_HARGA_KELOLA',session('id_cabang_aktif')))<button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalEditHarga{{ $item->id_daftar_harga }}">Edit</button><form class="d-inline" method="POST" action="{{ route('daftar-harga.status',$item->id_daftar_harga) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-{{ $item->status_aktif?'danger':'success' }}" onclick="return confirm('Ubah status daftar harga?')">{{ $item->status_aktif?'Nonaktifkan':'Aktifkan' }}</button></form>@endif</td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada daftar harga.</td></tr>@endforelse
</tbody></table></div><div class="card-footer">{{ $daftarHarga->links() }}</div></div>
@if(auth()->user()->memilikiHakAkses('DAFTAR_HARGA_KELOLA',session('id_cabang_aktif')))
<div class="modal fade" id="modalTambahHarga" tabindex="-1"><div class="modal-dialog modal-xl"><div class="modal-content"><form method="POST" action="{{ route('daftar-harga.simpan') }}">@csrf<div class="modal-header"><h5 class="modal-title">Tambah Daftar Harga</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('daftar_harga.partials.form',['item'=>null,'prefix'=>'tambah'])</div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan</button></div></form></div></div></div>
@foreach($daftarHarga as $item)<div class="modal fade" id="modalEditHarga{{ $item->id_daftar_harga }}" tabindex="-1"><div class="modal-dialog modal-xl"><div class="modal-content"><form method="POST" action="{{ route('daftar-harga.ubah',$item->id_daftar_harga) }}">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Edit {{ $item->nama_daftar_harga }}</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('daftar_harga.partials.form',['item'=>$item,'prefix'=>'edit'.$item->id_daftar_harga])</div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div></div>@endforeach
@endif
@endsection
@push('scripts')<script>
function aturNamaDetailHarga(wadah){wadah.querySelectorAll('[data-baris-detail-harga]').forEach((baris,index)=>baris.querySelectorAll('[data-field]').forEach(field=>field.name=`detail_harga[${index}][${field.dataset.field}]`));}
document.querySelectorAll('[data-wadah-detail-harga]').forEach(aturNamaDetailHarga);
document.addEventListener('click',event=>{const tambah=event.target.closest('[data-tambah-detail-harga]');if(tambah){const wadah=document.getElementById(tambah.dataset.target);const baris=wadah.querySelector('[data-baris-detail-harga]').cloneNode(true);baris.querySelectorAll('input').forEach(input=>input.value=input.dataset.field==='jumlah_minimum'?1:0);wadah.appendChild(baris);aturNamaDetailHarga(wadah);}const hapus=event.target.closest('[data-hapus-detail-harga]');if(hapus){const wadah=hapus.closest('[data-wadah-detail-harga]');if(wadah.querySelectorAll('[data-baris-detail-harga]').length>1)hapus.closest('[data-baris-detail-harga]').remove();aturNamaDetailHarga(wadah);}});
</script>@endpush
